# Generated by Django 4.2.6 on 2023-11-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SRN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.CharField(blank=True, max_length=10, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=30, null=True)),
                ('bloodgroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3, null=True)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
