# Generated by Django 4.2.6 on 2023-11-08 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('equipname', models.CharField(max_length=15)),
                ('buydate', models.DateField(blank=True, null=True)),
                ('availability', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('SRN', models.CharField(max_length=13, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contactno', models.CharField(blank=True, max_length=10, null=True)),
                ('emailid', models.EmailField(blank=True, max_length=30, null=True)),
                ('bloodgroup', models.CharField(blank=True, choices=[('A+', 'A+'), ('B+', 'B+'), ('AB+', 'AB+'), ('O+', 'O+'), ('A-', 'A-'), ('B-', 'B-'), ('AB-', 'AB-'), ('O-', 'O-')], max_length=3, null=True)),
                ('password', models.CharField(max_length=255)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allot_time', models.TimeField()),
                ('returntime', models.TimeField()),
                ('SRN', models.ForeignKey(db_column='SRN', on_delete=django.db.models.deletion.CASCADE, to='equipments.student')),
                ('equipid', models.ForeignKey(db_column='equipid', on_delete=django.db.models.deletion.CASCADE, to='equipments.equipment')),
            ],
            options={
                'db_table': 'allotments',
            },
        ),
    ]
