# Generated by Django 4.2.6 on 2023-11-16 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('equipname', models.CharField(max_length=15)),
                ('buydate', models.DateField(blank=True, null=True)),
                ('availability', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'equipment',
            },
        ),
        migrations.CreateModel(
            name='Allotment',
            fields=[
                ('allot_time', models.TimeField()),
                ('returntime', models.TimeField()),
                ('equipid', models.ForeignKey(db_column='equipid', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='equipments.equipment')),
                ('SRN', models.ForeignKey(db_column='SRN', on_delete=django.db.models.deletion.CASCADE, to='home.student')),
            ],
            options={
                'db_table': 'allotments',
            },
        ),
    ]
